basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  pb.CreateUserRequest:
    properties:
      Email:
        type: string
      Password:
        type: string
      Username:
        type: string
    type: object
  pb.CreateUserResponse:
    properties:
      ID:
        type: integer
    type: object
  pb.User:
    properties:
      Email:
        type: string
      Expires:
        type: string
      ID:
        type: integer
      Password:
        type: string
      Type:
        type: string
      Username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for WB Assistant
  title: WB Assistant API
  version: "1.0"
paths:
  /account/update:
    post:
      consumes:
      - application/json
      description: update account
      operationId: update-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pb.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: update account
      tags:
      - account
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pb.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pb.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
